spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/STUDY_DB
    username: postgres
    password: postgres
  batch:
    job:
      enabled: false   # Runnerで明示実行する
    jdbc:
      initialize-schema: always # PostgreSQL用にスキーマを初期化

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

batch:
  input:
    chunk-size: 100
    input-dir: D:/input
    input-file:
      customer: customers.csv