spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/batch
    username: postgres
    password: postgres
  batch:
    job:
      enabled: false   # Runnerで明示実行する

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    